### ISSUE TITLE
End-to-End Demo

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#113]
Following our discussions, we should come up with an example for Arc. I think the consensus is that we should implement an image processing pipeline for de-duplicating images through [hashing](https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html) (similar to what a system like [Halide](https://halide-lang.org) is capable of). To be able to express the computation, we may need primitives for [general image process operators](https://homepages.inf.ed.ac.uk/rbf/HIPR2/wksheets.htm) and I/O operations (e.g., through [`libjpeg`](http://libjpeg.sourceforge.net/]). We need to decide how exactly the pipeline should look, maybe by drawing/pseudo-coding it. Also, @frej, should we try an implement it bottom-up or top-down?

**Comment by frej** [comment]
I think we should do it top-down, i.e. sketch out how it should look like in arc-script. That can then control what we need to implement, both in arc-script and in the back-end.
