### ISSUE TITLE
Syntactic changes

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#12]
To make Arc more presentable, I suggest the following (non-backwards-breaking) syntactic changes:

# If-expressions

Old: `if(a,b,c)`
New:  `if a { b } else { c }`

# Select-expressions

Old: `select(a,b,c)`
New: `select a { b } else { c }`

# For-loops

Old: `for(a,b, |b,i,x| merge(b,x))`
New: `for (a,b) { |b,i,x| merge(b,x) }`

To preserve backwards compatibility, we can keep the old production rules in the grammar.

**Comment by Bathtor** [comment]
It's just the textual representation of an IR...it doesn't really matter if it looks pretty^^

For-loops should be `for (a, b) |b, i, x| { merge(b,x) }`, though. It doesn't make sense to have the lambda header within the curly braces delimiting the block.

If we are going for readability, I also have a slight preference for conditionals being bounded by parenthesis. I don't like the way conditionals read in Rust. So:
`if (a) { b } else { c }`
and
`select (a) { b } else { c }`

The `{...}` for the blocks could also be optional in this syntax, which shouldn't cause an issue as we don't have conditionals without an `else` block.

**Comment by segeljakt** [comment]
I agree `for (a, b) |b, i, x| { merge(b,x) }` looks better, we will have to change the struct grammar I think so that you can't have structs with one element.

**Comment by Bathtor** [comment]
Yeah, that is the disadvantage of these changes. They visually and syntactically interfere with structs.

**Comment by segeljakt** [comment]
Now that I look at it, it is a little confusing.

Old:
```
if(element < 0,
    { merge(negative_sink, element), even_sink, odd_sink },
    if(element % 2 == 0,
        { negative_sink, merge(even_sink, element), odd_sink },
        { negative_sink, even_sink, merge(odd_sink, element) },
    )
)
```

New:
```
if(element < 0)
    { merge(negative_sink, element), even_sink, odd_sink }
else if(element % 2 == 0)
    { negative_sink, merge(even_sink, element), odd_sink }
else
    { negative_sink, even_sink, merge(odd_sink, element) }
```

It might be best to wait a bit, eventually we can maybe change the struct syntax `{...}` to tuple syntax `(...)`.

```
if(element < 0)
    ( merge(negative_sink, element), even_sink, odd_sink )
else if(element % 2 == 0)
    ( negative_sink, merge(even_sink, element), odd_sink )
else
    ( negative_sink, even_sink, merge(odd_sink, element) )
```

**Comment by Bathtor** [comment]
If you check Erlang, which has similar record/tuple syntax to Weld, you see that they have gone a completely different way with their conditionals: http://erlang.org/doc/reference_manual/expressions.html#if
Essentially:
```erlang
if
   a -> 
      b;
   true ->
     c
end
```
But who likes `end` keywords, really?^^

**Comment by Bathtor** [comment]
Of course, we could replace `if` completely with some kind of `match` block (which is more what Erlang's `if`s are). It would be nice to eventually have that anyway.
But I don't think this should be a priority for now.
So...maybe close this issue for now and we'll come back to it later?

**Comment by segeljakt** [comment]
Alright
