### ISSUE TITLE
Clarify semantics

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#13]
Arc introduces new types which affect Weld's semantics. I will try to identify these in this issue:

* While Weld builders are linear (must be used exactly once), Arc builders are affine (can be used at most once).

* For-loops over Arc streams cannot be nested, but can contain inner for-loops over Weld collections.

```
// OK
for(source, sink, |b, x| merge(b, x));

// NOT OK
for(source1, sink1, |b1, x1| for(source2, sink2, |b2, x2| merge(b2, x2)));

// OK
for(source, sink, |b1, x1| merge(b1, result(for(vec, Appender, |b2, i2, x2| merge(b2, x2)))));

// NOT OK (for now)
for(vec, Appender, |b1, i1, x1|
  for(source, sink, |b2, x2| merge(b2, x2))
  merge(b1, x1)
)
```

* Weld expressions cannot contain Arc expressions (for now), for example:

```
// NOT OK
|source: Stream[i32], sink1: StreamAppender[i32], sink2: StreamAppender[i32], values: Vec[i32]|
let max_value = for(values, merger[i32, max], |b, i, x| merge(b, x));
if(len(values) > 5,
  for(source, sink1, |b, x| if(x > max_value, merge(b, x), b)),
  for(source, sink2, |b, x| if(x > max_value, merge(b, x), b))
);

// NOT OK
|source: Stream[i32], sink: StreamAppender[i32]|
let max_value = 5;
for(source, sink, |b, x| if(x > max_value, merge(b, x), b))

// OK
|source: Stream[i32], sink: StreamAppender[i32]|
let filtered = result(for(source, StreamAppender[i32], |b, x| if(x > 5, merge(b, x), b)));
let mapped = for(filtered, sink, |b, x| merge(b, x + 5));
```

It will be possible in the future to put Arc stuff in Weld, either by:
1. Converting the inner Arc-expressions to CUDFs and calling them from the outer Weld-expressions
2. Directly interpreting the outer Weld-expressions.
3. Combination of 1 and 2 (Use 1 for complex Weld expressions and 2 for lightweight Weld expressions)

* The main lambda function can take Arc and Weld-typed values as parameters, but cannot return Arc-typed values, .

```
// OK
|source: Stream[i32], sink: StreamAppender[i32]| ...

// OK
|source: Stream[i32], sink: StreamAppender[i32], param: i32| ...

// NOT OK
|source: Stream[i32]|(StreamAppender[i32]) ...
```

* For loops over Arc-streams cannot take Weld-builders. Conversely, for-loops over Weld-collections cannot take Arc-builders (for now):

```
// NOT OK
|source: Stream[i32], sink: StreamAppender[i32]|
  for(source, Appender[i32], |b, x| merge(b, x))

// NOT OK (for now)
|source: Stream[i32], sink: StreamAppender[i32]|
  for([1,2,3,4], sink, |b, x| merge(b, x))
```

* Merge operations on Arc builders need to be placed inside for-loops (for now):

```
// NOT OK (for now)
|source: Stream[i32], sink: StreamAppender[i32]|
  merge(b, 5);

// OK
|source: Stream[i32], sink: StreamAppender[i32]|
  for(source, sink, |b, x| merge(b, 5));
```

* Structs cannot contain both Arc types and Weld types, this would result in confusing situations like:

```
// NOT OK (???)
|source: Stream[i32], sink: StreamAppender[i32]|
  let x = Appender[i32];
  let y = StreamAppender[i32];
  let b = merge({x, y}, {5, 4});
  ...
```

It might still be possible, but I need to think more about how it could be implemented.

**Comment by senorcarbone** [comment]
Note: handle special "unbounded for", for stream operators that has i.e., no indexing
