### ISSUE TITLE
Cache artifacts generated by CI

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#277]
Caching of artifacts which are generated during CI could speedup compilation and testing times.

We could try the following (suggested by Frej):

1. Increase `ccache` to ~20G
2. Cache the target-directory used by the `arc-cargo`-script.

I will put this issue here until I have resolved it

**Comment by frej** [comment]
For 1 I would start with checking that the CI doesn't zap the ccache cache directory by default.
