### ISSUE TITLE
RFC: Additional code generation macros

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#300]
In `arcorn` we have the following macros:

* `enwrap!(variant, value)` - Enum construction
* `unwrap!(variant, value)` - Enum deconstruction
* `is!(variant, value)` - Enum check
* `#[rewrite] struct ...` - Generate conversion code for struct
* `#[rewrite] enum ...` - Generate conversion code for enum
* `#[rewrite] mod ...` - Generate arcon/arctime task

I think we could consider additionally to add macros for generating other kinds of boilerplate:

* `share_expr!(value)` - Wraps `value` inside `std::rc::Rc::new(std::rc::RefCell::new(value))`
* `share_type!(type)` - Wraps `type` inside `std::rc::Rc::new<std::rc::RefCell::new<type>>`
* `convert!(type)` - Expands to `<type as arc_script::arcorn::Convert>::T` to get the Sendable/Operable of a type.

@frej Is there anything which is tedious in MLIR to generate?

**Comment by frej** [comment]
> @frej Is there anything which is tedious in MLIR to generate?

The less details of the Rust implementation the MLIR-level needs to know the better it is.

If we have macros for sharing values, shouldn't we also have macros for accessing the boxed/rc:d value too? Or is that handled by some Rust magic?

**Comment by segeljakt** [comment]
Rust has [automatic dereferencing](https://doc.rust-lang.org/reference/expressions/field-expr.html?highlight=autoderef#automatic-dereferencing) for tpes which implement `Deref` and/or `DerefMut`.

Because
```rust
impl<T: ?Sized> Deref for Rc<T> {
    type Target = T;

    #[inline(always)]
    fn deref(&self) -> &T {
        &self.inner().value
    }
}
```

we can do

```rust
use std::rc::Rc;
use std::cell::RefCell;

struct Foo {
    x: i32,
    y: Rc<String>
}

fn main() {
    let a = Rc::new(Foo { x: 0, y: Rc::new("".to_owned())});
    let b = a.clone().x.clone();
    let c = a.clone().y.clone();
}
```

**Comment by segeljakt** [comment]
I suggest we skip `RefCell` mutability for the moment. It makes it slightly more annoying to generate, we would have to insert `.borrow()` and `.borrow_mut()` in certain places.
