### ISSUE TITLE
RFC: Rename `arcorn` and `arctime`

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#301]
On my computer the fuzzy search is always confusing `arcorn` and `arctime` for `arcon`. Would it be ok to rename them into something else, like `arc-codegen`/`arc-backend` and `arc-runtime`/`arc-kompact`? Let me know if you have other naming suggestions. Another thing is we could also pull `arcorn` up to the root of the repo since it is becoming more and more advanced.

**Comment by frej** [comment]
I don't mind, go ahead!

**Comment by segeljakt** [comment]
Closed with #307
