### ISSUE TITLE
Rust codegen for extern functions

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#362]
In the Arc standard library, we have:
```
extern type Cell[T];

extern def cell[T](T): Cell[T];
extern def update[T](Cell[T], T);
extern def read[T](Cell[T]): T;
```
On the Rust side we have correspondingly:
```rust
fn cell<T>(x: T, _: Context) -> Cell<T> {
    Cell { data: Rc::new(x) }
}
```
If one uses a cell to store `i32`, then we get:
```
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>">
```
This means the rest of the program expects there to be a Rust function named `cellsi32`, but this function does not exist, so any reference to it will result in a compilation error 😬 . A solution is to add the possibility of annotating a function with its unmangled identifier, for example:
```
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>"> {unmangled = cell}
```
Then we could generate Rust code such as this, which will delegate the call to the unmangled generic function.
```rust
#[rewrite]
#[inline(always)]
fn cellsi32(_0: i32) -> Cell<i32> {
    call!(cell(_0))
}
```
We could alternatively generate:
```rust
#[rewrite(unmangled = cell)]
extern fn cellsi32(i32) -> Cell<i32>;
```
And then expand it to the previous code.

**Comment by frej** [comment]
Does this issue have the right title? Isn't it about being able to add arbitrary annotations to function declarations, rather than calling external functions?

If we add two new attributes `arc.external` and `arc.annotation`

```MLIR
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>">
    attributes {rust.external, rust.annotation="#[rewrite(unmangled = cell)]"}
```
can give us:
```Rust
#[rewrite(unmangled = cell)]
extern fn cellsi32(i32) -> Cell<i32>;
```

**Comment by segeljakt** [comment]
Ok, it is also possible to generate:
```rust
#[rewrite(unmangled = cell)]
fn cellsi32(i32) -> Cell<i32> {}
```
The only requirement is that it must be parseable by Rust. I just put `extern` because then we can omit the function body.

**Comment by segeljakt** [comment]
That will work well 👍

**Comment by segeljakt** [comment]
I tried out the code generation part. It seems like 
```rust
#[rewrite(unmangled = "cell")]
fn cellsi32(i32) -> Cell<i32> {}
```
is the best approach.

The other does not compile:
```rust
#[rewrite(unmangled = cell)]
extern fn cellsi32(i32) -> Cell<i32>;
```
I forgot that you would need a block:
```rust
#[rewrite(unmangled = cell)]
extern {
    fn cellsi32(i32) -> Cell<i32>;
}
```

**Comment by frej** [comment]
I had a brain wave overnight. The functionality is already there without any need for rewite macros or inlining directives. Define `cellsi32` as an MLIR external function:
```MLIR
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>">
    attributes {arc.rust_name="cell"}
```

Whenever you call `cellsi32` you do:
```MLIR
%r = call @cellsi32(%0) : (si32) -> !arc.adt<"Cell<i32>">
```
and you will get the Rust
```Rust
let v1:Cell<i32> = cell(val!(v0), );
```

**Comment by segeljakt** [comment]
wow!

**Comment by frej** [comment]
There is a bug when the external function is used in a constant, #363 will fix that.

**Comment by segeljakt** [comment]
Is it possible to "instantiate" the function? for example:
```
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>">
    attributes {arc.rust_name="cell::<i32>"}
```
and generate
```
let v1:Cell<i32> = call!(cell::<i32>(val!(v0), ));
```
I'm trying to think how it will work if we want to create a function pointer.. 🤔

**Comment by frej** [comment]
Whatever is in the attribute gets passed on to Rust, so
```MLIR
func private @cellsi32(%_0: si32) -> !arc.adt<"Cell<i32>">
  attributes {arc.rust_name="cell::<i32>"}
```

will get you:

```Rust
let v1:Cell<i32> = call!(cell::<i32>(val!(v0), ));
```

Function pointers work to:

```MLIR
  func @caller1(%0: si32) -> !arc.adt<"Cell<i32>"> {
    %f = constant @cellsi32 : (si32) -> !arc.adt<"Cell<i32>">
    %r = call_indirect %f(%0) : (si32) -> !arc.adt<"Cell<i32>">
    return %r : !arc.adt<"Cell<i32>">
  }
```
will give you (if folding is turned off)
```Rust
pub fn caller1(v2: i32) -> Cell<i32> {
  let v3 : function!((i32,) -> Cell<i32>) = cell::<i32>;
  let v4:Cell<i32> = call_indirect!((val!(v3))(val!(v2), ));
  return val!(v4);
}
```

Will we need some extra Rust syntax for that?

**Comment by frej** [comment]
> When we create the function pointer we need to use `function!(...)`

 #364 should fix that.

**Comment by segeljakt** [comment]
I forgot to say, the idea of the logical tag is to preserve information about what a function pointer points to. This is needed when function pointers are transferred between OS processes (which can have different memory address space layouts). Functions are values so we need to create the logical tag simultaneously when creating the physical pointer, or else we might lose this information 👀
