### ISSUE TITLE
Rust code generation

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#44]
@frej I think you have made great progress on the Arc/Weld-MLIR lowering, is it possible or too early for us to attempt implementing an MLIR-Rust lowering for the currently supported operators?

**Comment by frej** [comment]
The next thing I want to do is to handle the Weld,`if` and `iterate` constructs as these will for the first time introduce LLVM regions which we haven't tried yet. After that it makes sense to try to produce rust.

**Comment by segeljakt** [comment]
Ok, for `if`, `loop.if` might suffice: https://mlir.llvm.org/docs/Dialects/LoopOps/

**Comment by segeljakt** [comment]
@frej Before lowering to Rust or a Rust dialect, I think we need to lower into a dialect which turns the Arc expressions into a basic block format, similar to how Weld translates into a Sequential IR ([SIR](https://github.com/weld-project/weld/tree/master/weld/src/sir)). I will investigate more how this lowering works.

**Comment by frej** [comment]
I'm not sure that's the right way to go if we are to target rust. For the rust compiler to do a good job I don't think we can give it a soup of blocks and gotos. As far as I can tell, rust does not have gotos. We can always rewrite an arbitrary goto structure into a switch, but I think that could confuse terminally confuse the Rust optimizer and/or safety checker.

**Comment by segeljakt** [comment]
Ok, you're right, basic blocks are probably too low level. I'm unsure how we should translate into Rust. One option can be to translate into the Rust `std::iter::Iterator` API.

Every expression in Weld is like a 1-to-N FlatMap. I think when N=1, translation is very easy:
```
|foo: vec[i32]|
result(for(foo, appender[i32] |b, i, v| merge(b.$1, v+1)))
// foo.flat_map(|v| vec![v + 1]).collect();
```
But when N>1, there is no Rust iterator adaptor I know of which we can translate into:
```
|foo: vec[i32]|
result(for(foo, {appender[i32], appender[i32]} |b, i, v| { merge(b.$0, v+1), merge(b.$1, v-1) }))
// ???
```
Therefore, maybe it is better to directly translate into loops. Rust's iterator API compiles down into loops either way. Alternatively we could try create an API on the Rust side which we can translate into.

**Comment by segeljakt** [comment]
Closing (outdated)
