### ISSUE TITLE
Migrate from mlir-opt to mlir-translate

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arc#73]
@frej From a conversation on Discord with MLIR developer `@TheRiddler`:

![image](https://user-images.githubusercontent.com/15143039/76036033-47300b80-5f43-11ea-98af-b5dc4b6a2731.png)

This will probably make our lives easier 😄

**Comment by frej** [comment]
Probably, as soon as we figure out how to use the framework. There isn't any documentation (at least `git grep ranslate`) does not find any. But at least there is code to look at.

**Comment by segeljakt** [comment]
I'll investigate

**Comment by frej** [comment]
Until we can add a custom mlir-tblgen backend without maintaining a local fork of the LLVM module I don't think migrating to mlir-translate is worth it.

**Comment by segeljakt** [comment]
I think we solved this, so I can close for now
